# Python para análise de dados

Introdução à biblioteca numpy

In [127]:
# importa a biblioteca numpy
import numpy as np

In [128]:
# criando um array de uma dimensão apenas
one_dim = np.array([1,2,3,4])

# Criando um array de duas dimensões
two_dim = np.array([(1,2,3),(4,5,6)])

In [129]:
type(one_dim)

numpy.ndarray

In [130]:
# vizualizando no número de dimensões do array
print( "Dimensão arr 1:" ,one_dim.ndim )
print( "Dimensão arr 2:" ,two_dim.ndim )

Dimensão arr 1: 1
Dimensão arr 2: 2


In [131]:
# Imprimindo o array
one_dim

array([1, 2, 3, 4])

In [132]:
# Imprimindo o array
two_dim

array([[1, 2, 3],
       [4, 5, 6]])

In [133]:
# Cria um array de números aleatórios.
# Um array de 5 linhas e 2 colunas
np.random.random((5,2))

array([[0.06823948, 0.11285721],
       [0.44534391, 0.73701018],
       [0.20821906, 0.03758016],
       [0.1070686 , 0.57790687],
       [0.20963001, 0.92742056]])

In [134]:
# Cria um array com valores esparsos iniciando com o valor 10, menor que 50 e incrementando de 5 em 5

# Ex:
# np.arange(10,100,9) # até <100 de 10 em 10
# np.arange(0,20,2) # até <20 de 2 em 2
np.arange(10,50,5) # até <50 de 5 em 5

array([10, 15, 20, 25, 30, 35, 40, 45])

In [135]:
# Cria um array linear de 0 a 2 de no máximo 9 elementos

# EX:
# np.linspace(0,2,10) # from 0 to 2 max 10
# np.linspace(-1,1,3) # from -1 to 1 max 3
np.linspace(0,2,9) # from 0 to 2 max 9

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])

In [136]:
# Cria um array de valores zeros
# Cria um array com 3 linhs e 4 dimensões
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

# Numpy arrays Vs Listas

- Arrays numpy permitem fazermos operações em arrarys inteiros de forma rápida.
- Listas não permitem operações em todos os elementos da lista.
- Para operações em todos os elementos é preciso interar sobre toda a lista.
- Listas em Python armazenam diferentes tipos de objetos.
- Arrays Numpy considera todos os elementos de tipos distintos como strings

In [137]:
# Criando uma lista em Python.
lista = [1,2,3]

In [138]:
lista

[1, 2, 3]

In [139]:
# Multiplicar valores da lista por 2.
lista * 2

[1, 2, 3, 1, 2, 3]

In [140]:
# Transforme a variável lista em um array Numpy
lista = np.array([1,2,3])

In [141]:
type(lista)

numpy.ndarray

In [147]:
# Multiplicando cada elemento por 2
lista * 2

array([2, 4, 6])

In [148]:
# Calcular IMC de pessoas.
pesos = [67,81,120,90]
altura = [1.68,1.70,1.75,1.85]

In [ ]:
# Faz o calculo usando as listas
# isso imprimirá um erro, pois não é possível realizar operações matemáticas entre duas listas python
pesos / altura ** 2

In [149]:
# Transforma as listas em arrays numpy
pesos = np.array(pesos)
altura = np.array(altura)

In [150]:
# Faz o calculo em imprime cada valor 
pesos / altura ** 2

array([23.73866213, 28.02768166, 39.18367347, 26.29656684])

In [151]:
# Arrays Numpy armazenam elementos como Strings quando estes não são inteiros ou floats,
# ou seja,quando não são homogêneos
a = np.array([1,2,'Casa',True])

In [152]:
a

array(['1', '2', 'Casa', 'True'], dtype='<U21')

In [ ]:
# Imprimirá um erro, pois não é possível realizar operações matemáticas em um array de strings
a*2