# Métodos e Atributos Úteis dos arrays Numpy

In [1]:
# Importa a biblioteca numpy
import numpy as np

In [2]:
# Cria um array de duas dimensões
two_dim = np.array([(1,2,3),(4,5,6)])

In [3]:
# Exibe esse array
two_dim

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
# Métodos disponíveis ( digitar o . e pressionar tab ).
two_dim.

In [6]:
# Retorna a forma do array no formato (linhas,colunas).
two_dim.shape

(2, 3)

In [7]:
# Retorna a quantidade de dimensões que um array possui
two_dim.ndim

2

In [8]:
# Imprimindo o valor máximo do array.
two_dim.max()

6

In [10]:
# Imprimindo o valor mínimo.
two_dim.min()

1

In [12]:
# Imprimindo o valor médio.
two_dim.mean()

3.5

In [14]:
# Imprime o desvio padrão do array.
two_dim.std()

1.707825127659933

In [15]:
# Imprime o tipo de dados contidos no Array
two_dim.dtype

dtype('int64')

In [19]:
# Imprime a quantidade de elementos contidos no array
two_dim.size

6

In [22]:
# Mostra o tamanho dos itens em bytes
two_dim.itemsize

8

In [24]:
# Somando todos os elementos do array
two_dim.sum()

21

# Transfornando Arrays

In [25]:
two_dim

array([[1, 2, 3],
       [4, 5, 6]])

In [28]:
# Gera a transposta da Matriz (Linha -> Coluna)
two_dim.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [29]:
two_dim

array([[1, 2, 3],
       [4, 5, 6]])

In [30]:
# Transforma em uma matriz de uma linha.
# É muito comum em bibliotecas como scikit-learn e Keras
two_dim.reshape(-1)

array([1, 2, 3, 4, 5, 6])

In [35]:
# Cria um array random com 5 linhas e 3 colunas
tree = np.random.random((5,3))

In [36]:
tree.shape

(5, 3)

In [37]:
tree

array([[0.43182109, 0.37433438, 0.63957902],
       [0.02927644, 0.7643892 , 0.20785126],
       [0.90364247, 0.27460424, 0.7822667 ],
       [0.22686172, 0.23854149, 0.68208962],
       [0.90105052, 0.10658118, 0.98624853]])

In [39]:
# Transforma em uma matriz com 3 linhas e 5 colunas
tree.reshape(3,5)

array([[0.43182109, 0.37433438, 0.63957902, 0.02927644, 0.7643892 ],
       [0.20785126, 0.90364247, 0.27460424, 0.7822667 , 0.22686172],
       [0.23854149, 0.68208962, 0.90105052, 0.10658118, 0.98624853]])

In [46]:
# Transorma a matriz em uma array linear, ou seja todos os valores em uma mesma lista
tree.reshape(-1).shape

(15,)

In [47]:
tree.reshape(-1)

array([0.43182109, 0.37433438, 0.63957902, 0.02927644, 0.7643892 ,
       0.20785126, 0.90364247, 0.27460424, 0.7822667 , 0.22686172,
       0.23854149, 0.68208962, 0.90105052, 0.10658118, 0.98624853])

In [53]:
# Tranforma a matriz em uma outra matriz que possui apenas 1 coluna
t = tree.reshape(1,15)
t.shape

(1, 15)

In [55]:
t

array([[0.43182109, 0.37433438, 0.63957902, 0.02927644, 0.7643892 ,
        0.20785126, 0.90364247, 0.27460424, 0.7822667 , 0.22686172,
        0.23854149, 0.68208962, 0.90105052, 0.10658118, 0.98624853]])

In [57]:
two_dim

array([[1, 2, 3],
       [4, 5, 6]])

In [58]:
# Adicionando elementos a um array
two_dim = np.insert(two_dim,0,10)

In [59]:
# Transforma em um array de uma linha
two_dim

array([10,  1,  2,  3,  4,  5,  6])

In [60]:
# Apagando o elementos da primeira posição do array.
two_dim = np.delete(two_dim,[0])

In [62]:
two_dim

array([1, 2, 3, 4, 5, 6])

In [63]:
# Gerando um arquivo .txt a partir de um array
np.savetxt("dataset_array.txt",two_dim,delimiter=',')