# Python para Análise de Dados - Numpy

### Acessando Dimensões no Array

In [1]:
import numpy as np

In [4]:
# Gera um array aleatório de 10 linhas e 2 colunas
# Formato linha,coluna
my_array = np.random.random([10,2])

In [5]:
my_array

array([[0.78328371, 0.91141666],
       [0.86946007, 0.00504466],
       [0.02412553, 0.89571206],
       [0.29344429, 0.0940585 ],
       [0.77232065, 0.14590887],
       [0.95959494, 0.76029078],
       [0.97534521, 0.66773908],
       [0.22882473, 0.45232747],
       [0.8374253 , 0.26550332],
       [0.50383531, 0.0631942 ]])

In [7]:
# Imprime a primeira linha
my_array[0]

array([0.78328371, 0.91141666])

In [10]:
# Imprime o primeiro elemento da coluna 0 ( 1 coluna )
my_array[0][0]

0.783283713267006

In [11]:
# Imprime o primeiro elemento da coluna 1 ( 1 coluna )
my_array[0][1]

0.9114166584431845

In [13]:
# Segundo elemento da coluna 1
my_array[1][1]

0.00504465751206673

In [14]:
# O Segundo elemento da coluna escrito comvirgula
# no formato [linha,coluna]
my_array[1,1]

0.00504465751206673

In [19]:
# Imprimindo os 3 primeiros valores da coluna 1
my_array[:3,1]

array([0.91141666, 0.00504466, 0.89571206])

In [25]:
# Imprime todas as linhas da (coluna 1) * 10
my_array[:,1] * 10

array([9.11416658, 0.05044658, 8.95712055, 0.94058496, 1.45908865,
       7.60290776, 6.6773908 , 4.52327467, 2.65503322, 0.63194199])

In [27]:
# Comparação retorna indices
my_array > 0.5

array([[ True,  True],
       [ True, False],
       [False,  True],
       [False, False],
       [ True, False],
       [ True,  True],
       [ True,  True],
       [False, False],
       [ True, False],
       [ True, False]])

In [31]:
# Acessando valores por índices
# Comparação retorna indices
my_array[ my_array > 0.5 ]

array([0.78328371, 0.91141666, 0.86946007, 0.89571206, 0.77232065,
       0.95959494, 0.76029078, 0.97534521, 0.66773908, 0.8374253 ,
       0.50383531])

### Carregar Arrays Numpy a partir de arquivos de texto

In [32]:
import numpy as np

In [33]:
# Lendo um arquivo do tipo .txt
dataset = np.loadtxt('dataset_array.txt',delimiter=',')

In [34]:
dataset.shape

(6,)

In [35]:
dataset

array([1., 2., 3., 4., 5., 6.])

In [36]:
# Carregando um arquivo dividindo em 3 arrays
a, b, c = np.loadtxt('dataset_valores.txt',skiprows=1,unpack=True)

In [37]:
# Array a
a

array([0.4839, 0.1292, 0.1781, 0.7676, 0.5993])

In [38]:
# Array b
b

array([0.4536, 0.6875, 0.3049, 0.5801, 0.4357])

In [39]:
# Array c
c

array([0.3561, 0.6565, 0.8928, 0.2038, 0.741 ])

In [42]:
# Carrega o arquivo ignorando as 2 primeiras linhas e preenchendo os valores vazio por 0
# Obs: os valores string também são convertidos!!

dataset = np.genfromtxt('dataset_valores_vazio.txt',skip_header=2,filling_values=0)

In [43]:
# Imprimindo o dataset
dataset

array([[0.4839, 0.4536, 0.3561],
       [0.1292, 0.6875, 0.    ],
       [0.1781, 0.3049, 0.8928],
       [0.    , 0.5801, 0.2038],
       [0.5993, 0.4357, 0.741 ]])